### PR TITLE
I have added google rest api (google place autocomplete) in dialog wi…

### PR DESCRIPTION
**Pull request by mala9974025544**
…th autocomplete functionality

## Description
I Implement Google place auto complete rest API in Dialog 
screen1
screen2
screen3

## Screenshots
Before | After
---|---
 | 

## Mandatory GIF
mandatory

### CODE REVIEW

**Comment by mala9974025544** [comment]
I have added Google place autocomplete rest api in dialog

**Comment by ferranpons** [comment]
@mala9974025544 many thanks for your contribution. I'll review it ASAP.

**Comment by ferranpons** [comment]
@mala9974025544 I'm sorry but in order to be able to merge the PR you would need to solve the build issues

**Comment by mala9974025544** [comment]
Can you please mention the build issues.because i don't have any build issues

**Comment by ferranpons** [comment]
@mala9974025544 I'm sorry but your PR has a lot of build errors, please check out the travis log:

[https://travis-ci.org/github/AdevintaSpain/Leku/builds/752763219](https://travis-ci.org/github/AdevintaSpain/Leku/builds/752763219)

**Comment by DJPretorius** [comment]
Hi @mala9974025544.

This is really needed and very cool functionality you built in. Would you please look into the build failures so that your changes can be made part of this great package?
Otherwise your hard work would have been in vane.

Thanks and keep contributing.

**Comment by mala9974025544** [comment]
Hi Daniel

*Hope you doing well!!*
*Can you help me out how to solve that error ?*
*i mean where to find it, i have no error in my code.*


*Thanks & Regards*
*Mala Ruparel*
*Sr. Software Engineer*
9664562685
| ***@***.***
https://www.smartsensesolutions.com
[image: https://www.facebook.com/malvika.ruparel]
<http://www.facebook.com/username> [image: www.linkedin.com/in/
mala-ruparel-aa682772] <http://us.linkedin.com/username>
<http://instagram.com/username>

**Comment by ferranpons** [comment]
@mala9974025544 I'm sorry but I had to close the PR because the required changes to make the CI pass where not met. Due to there are a lot of changes since your last commit I suggest you to review and update your code to meet the requirements and try to submit a new Pull Request.

Many thanks for your contribution and effort to add a new functionality to this library. I hope we can include your contribution the next time.

If you have questions or want to discuss it please leave a message.

**Pull request closed without merging**
